# Generated by Django 4.2.7 on 2023-12-07 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='faculty',
        ),
    ]
