# Generated by Django 4.2.7 on 2023-12-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_remove_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True,
                                      help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                      verbose_name='active'),
        ),
    ]
