# Generated by Django 4.2.7 on 2023-12-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
