# Generated by Django 4.2.7 on 2023-12-10 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
