# Generated by Django 4.2.7 on 2023-12-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True,
                                      help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                      verbose_name='active'),
        ),
    ]
