# Generated by Django 5.0 on 2023-12-14 16:37

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
