# Generated by Django 5.0 on 2023-12-14 16:52

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
