# Generated by Django 5.0 on 2023-12-16 04:39

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_lecturer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
